name: Publishing a Snapshot

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process'
  JAVA_VERSION: 11
on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
permissions:
  contents: read
jobs:
  publish:
    name: Publish library as SNAPSHOT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Overwriting library version for snapshot
        run: SNAPSHOT_VERSION=$(grep '^MY_LIB_VERSION.*$' gradle.properties | sed 's/\(.*\) \(.*\)/\2/')-SNAPSHOT-$(git rev-parse --short HEAD)
      - run: sed -i "s/MY_LIB_VERSION.*$/MY_LIB_VERSION = $(echo $SNAPSHOT_VERSION)/g" gradle.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Publish to GitHub packages repository
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publishReleasePublicationToGitHubPackagesRepository
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          REPO_CREDENTIAL_USER: ${{ secrets.REPO_CREDENTIAL_USER }}
          REPO_CREDENTIAL_PASSWORD: ${{ secrets.REPO_CREDENTIAL_PASSWORD }}