name: Publishing a release

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process'
  JAVA_VERSION: 11
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  publish:
    name: Publish
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
      - name: Create service_account.json
        run: echo '${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}' > service_account.json
      - name: get properties from service_account.json
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: "./service_account.json"
      - run: |
          echo ${{steps.json_properties.outputs.type}}
          echo ${{steps.json_properties.outputs.project_id}}
          echo ${{github.run_number}}
      - name: Get the next version code
        id: last_version_code
        uses: mmachado53/google-play-next-version-code@v0.0.5
        with:
          serviceAccountJsonFile: service_account.json
          packageName: wayakdev.sample.app
      - run: |
          echo ${{steps.last_version_code.outputs.versionCode}}
      - name: Bump version code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{steps.last_version_code.outputs.versionCode}}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Assemble bundleRelease
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.BUNDLE_SIGNING_KEY }}
          alias: ${{ secrets.BUNDLE_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.BUNDLE_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.BUNDLE_KEY_PASSWORD }}
      - name: Deploy to Internal
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: wayakdev.sample.app
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
      - name: Assemble APK
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: assembleDebug
      - name: Printing Signing Report
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: signingReport
      - name: Upload APK to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Publish to GitHub packages repository
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publishReleasePublicationToGitHubPackagesRepository
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          REPO_CREDENTIAL_USER: ${{ secrets.REPO_CREDENTIAL_USER }}
          REPO_CREDENTIAL_PASSWORD: ${{ secrets.REPO_CREDENTIAL_PASSWORD }}


  sync:
    name: Publish to public repo
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create deploy folder
        run: mkdir deploy
      - name: Copying the necessary files to the deploy folder
        run: |
          cp -R version.txt ./app ./gradle .gitignore LICENSE build.gradle gradle.properties gradlew gradlew.bat settings.gradle ./deploy
          mkdir -p ./deploy/.github/workflows && cp -R .github/workflows-public/. ./deploy/.github/workflows
      - name: Remove private library references
        run: sed -i "s/include ':mylibrary'//g" ./deploy/settings.gradle && sed -i "s/implementation project(':mylibrary')/implementation \"wayakdev.sample:sample-library:\$libVersion\"/g" ./deploy/app/build.gradle
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
      - name: Build sample code from the deploy folder
        run: cd ./deploy && ./gradlew build
      - name: Pushes to the public repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          source-directory: 'deploy'
          destination-github-username: 'mmachado53'
          destination-repository-name: 'android-sample-lib-public'
          user-email: mmachado53@gmail.com
          target-branch: main
      - name: Create release in public repo
        uses: ncipollo/release-action@v1
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          tag: ${{ github.ref_name }}
          repo: "android-sample-lib-public"
          owner: "mmachado53"
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}